apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mongo-frontend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mongo-frontend
    app.kubernetes.io/part-of: mongo-db-example
  name: mongo-frontend
  namespace: aaaa-studio
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: mongo-frontend
status:
  loadBalancer: {}
